### PR TITLE
added to the intake page

### PR DESCRIPTION
**Pull request by chivesonions**

### CODE REVIEW

**Review by mattsmithtaiko — CHANGES_REQUESTED** [review]
Looks like the threshold respelling got pulled into this. Switch to main, do git pull, then merge main into this branch. That should fix it.

**Review by chivesonions — COMMENTED** [review]
just did the pulling and merging, i checked the branch and it seems that the spelling is correct now

**Review by mattsmithtaiko — CHANGES_REQUESTED** [review]
Hmm I'm still seeing the change. After pulling and merging, did you push your branch again?

**Review by chivesonions — COMMENTED** [review]
hmm it looks like i didn't my bad, just pushed

**Comment by mattsmithtaiko** [comment]
Huh, still not seeing any change. Maybe do the whole thing one more time?
- Switch to main
- git pull
- Switch to your branch
- git merge main
- Push your branch

**Comment by chivesonions** [comment]
just did all of this, is it working now?

**Comment by mattsmithtaiko** [comment]
Hmmm I still see that one commit... Next time we're at a meeting together let's figure it out in-person. It'll be a good exercise in learning how to fix git issues :)

**Review by mattsmithtaiko — APPROVED** [review]

**Pull request merged**
